### ISSUE TITLE
Join a game

### ISSUE THREAD

**Issue by JulieL999** [dapopovic/SE2_Anti-Monopoly#14]
## Story

As a user, I want to be able to join a game. 

## Acceptance Criteria

Scenario: The user chooses the "Join game" item in the main menu

Given that the user wants to join a game,  
when he clicks the "Join game" button,  
then he can join an already created game after entering a correct game PIN.

## Notes

For this user story, it is just necessary to implement UI

## Definition of Done

* [x] Custom Branch created
* [x] Pass the Quality Gates

**Comment by FairTradeOrange** [comment]
Note: "For this user story, it is just necessary to implement UI" is obsolete.
